export const LISTING_DUMMY_DATA = [
  {
    title: "Inceptos",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incidid...",
    created: "Jan 10, 2025",
    creator: "Tim Cheney",
    scans: 46,
    likes: 37,
    comments: 26,
    shares: 12,
    status: "active",
  },
  {
    title: "Fermentum Venenatis Tortor",
    description: "Duis aute irure dolor in reprehenderit in voluptate",
    created: "Jan 10, 2025",
    creator: "Joan Smith",
    scans: 46,
    likes: 37,
    comments: 26,
    shares: 12,
    status: "active",
  },
  {
    title: "Malesuada Ipsum",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    created: "Jan 10, 2025",
    creator: "Cael Curry",
    scans: 46,
    likes: 37,
    comments: 26,
    shares: 12,
    status: "active",
  },
  {
    title: "Venenatis Mollis",
    description:
      "Tristique senectus et netus et malesuada fames ac turpis. Sit amet consectetur adipiscing elit...",
    created: "Jan 10, 2025",
    creator: "Lane Gill",
    scans: 46,
    likes: 37,
    comments: 26,
    shares: 12,
    status: "inactive",
  },
  {
    title: "Magna Malesuada",
    description: "Duis aute irure dolor in reprehenderit in voluptate",
    created: "Jan 10, 2025",
    creator: "David Kemp",
    scans: 46,
    likes: 37,
    comments: 26,
    shares: 12,
    status: "inactive",
  },
  {
    title: "Parturient Lorem",
    description:
      "Ullamcorper morbi tincidunt ornare massa eget. Quam viverra orci sagittis eu volutpat odio faci...",
    created: "Jan 10, 2025",
    creator: "Mollie Morris",
    scans: 46,
    likes: 37,
    comments: 26,
    shares: 12,
    status: "inactive",
  },
];

export const TEAM_MEMBER_DATA = [
  {
    name: "Joan Smith",
    email: "tranthuy.nute@gmail.com",
    added_on: "Jan 10, 2025",
    role: "admin",
  },
  {
    name: "Mary Richards",
    email: "danghoang87hl@gmail.com",
    added_on: "Jan 10, 2025",
    role: "editor",
  },
  {
    name: "Samantha Evans",
    email: "nvt.isst.nute@gmail.com",
    added_on: "Jan 10, 2025",
    role: "editor",
  },
  {
    name: "Maria Stevens",
    email: "vuhaithuongnute@gmail.com",
    added_on: "Jan 10, 2025",
    role: "editor",
  },
  {
    name: "James Ruskin",
    email: "thuhang.nute@gmail.com",
    added_on: "Jan 10, 2025",
    role: "editor",
  },
  {
    name: "David Kemp",
    email: "ckctm12@gmail.com",
    added_on: "Jan 10, 2025",
    role: "editor",
  },
];

export const MEDIA_CARD_DATA = [
  {
    id: 1,
    title: "Odio ut sem",
    tags: ["Deportes", "Deportes", "Economía"],
    thumbnail:
      "https://plus.unsplash.com/premium_photo-1669278728736-7e8cec06c3e0?q=80&w=928&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    videoUrl: "#",
  },
  {
    id: 2,
    title: "Mi eget mauris",
    tags: ["Deportes", "Deportes", "Economía", "Economía"],
    thumbnail:
      "https://images.unsplash.com/photo-1551999158-75d41e4860a5?q=80&w=928&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    videoUrl: "#",
  },
  {
    id: 3,
    title: "Eget nulla facilisi",
    tags: ["Tecnología", "Moda", "Salud", "Salud", "Moda"],
    thumbnail:
      "https://images.unsplash.com/photo-1744424945597-d695380d092a?q=80&w=774&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    videoUrl: "#",
  },
  {
    id: 4,
    title: "Odio ut sem",
    tags: ["Deportes", "Deportes", "Economía"],
    thumbnail:
      "https://images.unsplash.com/photo-1747573285214-b6a4246ee727?q=80&w=774&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    videoUrl: "#",
  },
  {
    id: 5,
    title: "Mi eget mauris",
    tags: ["Deportes", "Deportes", "Economía", "Economía"],
    thumbnail:
      "https://images.unsplash.com/photo-1746950862850-bf965eaa7aaa?q=80&w=1740&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    videoUrl: "#",
  },
  {
    id: 6,
    title: "Eget nulla facilisi",
    tags: ["Tecnología", "Moda", "Salud", "Salud", "Moda"],
    thumbnail:
      "https://plus.unsplash.com/premium_photo-1746253496816-4079a5880786?q=80&w=1658&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    videoUrl: "#",
  },
  {
    id: 7,
    title: "Eleifend id rhoncus",
    tags: ["Noticias", "Moda", "Deportes", "Deportes", "Tecnología"],
    thumbnail:
      "https://images.unsplash.com/photo-1745136028303-7c01bae7eb6a?q=80&w=774&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    videoUrl: "#",
  },
  {
    id: 8,
    title: "Integer vitae justo",
    tags: ["Deportes", "Tecnología", "Moda", "Moda", "Noticias"],
    thumbnail:
      "https://images.unsplash.com/photo-1522743791393-522312deeebf?q=80&w=916&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    videoUrl: "#",
  },
  {
    id: 8,
    title: "Libero enim sed",
    tags: ["Salud", "Noticias", "Tecnología"],
    thumbnail:
      "https://images.unsplash.com/photo-1665686304312-16e3a16be0ed?q=80&w=1740&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    videoUrl: "#",
  },
  {
    id: 9,
    title: "Quam leo lacus",
    tags: ["Noticias", "Deportes", "Salud", "Noticias"],
    thumbnail:
      "https://plus.unsplash.com/premium_photo-1744980204756-f6873a3d9c92?q=80&w=1740&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    videoUrl: "#",
  },
  {
    id: 10,
    title: "Vitae justo eget",
    tags: ["Salud", "Noticias", "Salud", "Tecnología", "Deportes"],
    thumbnail:
      "https://images.unsplash.com/photo-1746483965832-40cd64149b4f?q=80&w=1738&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    videoUrl: "#",
  },
  {
    id: 10,
    title: "Elit eget gravida",
    tags: ["Turismo", "Deportes", "Economía", "Deportes", "Moda"],
    thumbnail:
      "https://images.unsplash.com/photo-1749022812693-84015fc54817?q=80&w=872&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    videoUrl: "#",
  },
  {
    id: 11,
    title: "Ac ut consequat",
    tags: ["Moda", "Noticias", "Economía"],
    thumbnail:
      "https://plus.unsplash.com/premium_photo-1748777172658-64e15e2dd1bd?q=80&w=774&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    videoUrl: "#",
  },
  {
    id: 12,
    title: "Quis enim lobortis",
    tags: ["Noticias", "Moda", "Turismo", "Salud", "Moda"],
    thumbnail:
      "https://plus.unsplash.com/premium_photo-1746718184985-ac69ce0068e4?q=80&w=774&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    videoUrl: "#",
  },
  {
    id: 13,
    title: "Parturient sociis sodales",
    tags: ["Turismo", "Deportes", "Moda", "Moda", "Deportes"],
    thumbnail:
      "https://plus.unsplash.com/premium_photo-1746896139463-998fe8fff951?q=80&w=872&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    videoUrl: "#",
  },
];

export const DUMMY_SUPPORT_CHATS = [
  {
    name: "Jaylee Mueller",
    time: "01:08 pm",
    message: "Hey, how’s your project going?",
    isSender: false,
  },
  {
    name: "You",
    time: "01:08 pm",
    message: "Hi Jaylee! It’s going well, just wrapping up the final part.",
    isSender: true,
  },
  {
    name: "Jaylee Mueller",
    time: "01:08 pm",
    message:
      "That’s awesome. Did you manage to fix the issue you had yesterday?",
    isSender: false,
  },
  {
    name: "You",
    time: "01:08 pm",
    message: "Yes, I refactored some code and now it’s working smoothly.",
    isSender: true,
  },
  {
    name: "Jaylee Mueller",
    time: "01:08 pm",
    message: "Nice! Are you planning to submit it before the weekend?",
    isSender: false,
  },
  {
    name: "You",
    time: "01:08 pm",
    message: "Yeah, hopefully by Friday evening. Then I can finally relax!",
    isSender: true,
  },
  {
    name: "Jaylee Mueller",
    time: "01:08 pm",
    message: "Haha, you deserve it. Maybe we should celebrate afterwards?",
    isSender: false,
  },
  {
    name: "You",
    time: "01:08 pm",
    message: "Sounds great! Let’s plan something fun.",
    isSender: true,
  },
  {
    name: "Jaylee Mueller",
    time: "01:08 pm",
    message: "Cool, I’ll think of some ideas and let you know.",
    isSender: false,
  },
  {
    name: "You",
    time: "01:08 pm",
    message: "Perfect 👍 thanks Jaylee!",
    isSender: true,
  },
];

export const scanData = [
  {
    title: "Today",
    value: 2,
    label: "Scans",
  },
  {
    title: "Last 7 days",
    value: 18,
    label: "Scans",
  },
  {
    title: "Last 30 days",
    value: 34,
    label: "Scans",
  },
  {
    title: "Last 90 days",
    value: 70,
    label: "Scans",
  },
];

export const mediaCards = [
  {
    id: 1,
    title: "Fermentum Venenatis Tortor",
    description: "Duis aute irure dolor in reprehenderit in voluptate",
    image:
      "https://images.unsplash.com/photo-1745179177535-f83fb38821a2?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=774",
    likes: 37,
    shares: 12,
    comments: 37,
    saves: 12,
    type: "sms",
    label: "SMS Message",
    message: "Duis aute irure dolor in reprehenderit in voluptate",
    button: {
      text: "Learn more",
      color: "black",
      link: "#",
    },
  },
  {
    id: 2,
    title: "Fermentum Venenatis Tortor",
    description: "Duis aute irure dolor in reprehenderit in voluptate",
    image:
      "https://images.unsplash.com/photo-1490730141103-6cac27aaab94?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=1740",
    likes: 37,
    shares: 12,
    comments: 37,
    saves: 12,
    type: "web",
    label: "Web Link",
    message: "https://www.example.com",
    button: {
      text: "Shop Now",
      color: "#2E7CF6",
      link: "https://www.example.com",
    },
  },
  {
    id: 3,
    title: "Fermentum Venenatis Tortor",
    description: "Duis aute irure dolor in reprehenderit in voluptate",
    image:
      "https://images.unsplash.com/photo-1495366821225-0a3d30d20b5e?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=1740",
    likes: 37,
    shares: 12,
    comments: 37,
    saves: 12,
    type: "call",
    label: "Call",
    message: "15551231234",
    button: {
      text: "Call Now",
      color: "#263577",
      link: "tel:15551231234",
    },
  },
];

export const USERS_AND_ACCOUNTS = [
  {
    account_id: "ACC001",
    account_name: "Techify Labs",
    email: "admin@techifylabs.com",
    platforms: ["iOS", "Android"],
    current_plan: "growth",
    status: "active",
    created_at: "2024-03-15T10:45:00Z",
    last_active_at: "2025-12-09T18:22:00Z",
    total_campaigns: 42,
    storage_used: 12.5,
    hits_this_month: 185000,
    hit_limit: 250000,
  },
  {
    account_id: "ACC002",
    account_name: "BlueWave Media",
    email: "contact@bluewave.io",
    platforms: ["iOS"],
    current_plan: "starter",
    status: "active",
    created_at: "2024-09-01T09:30:00Z",
    last_active_at: "2025-12-08T11:10:00Z",
    total_campaigns: 7,
    storage_used: 850,
    hits_this_month: 9200,
    hit_limit: 20000,
  },
  {
    account_id: "ACC003",
    account_name: "TrendBoost",
    email: "support@trendboost.com",
    platforms: ["Android"],
    current_plan: "pro_plus",
    status: "suspended",
    created_at: "2023-11-22T16:15:00Z",
    last_active_at: "2025-11-29T09:05:00Z",
    total_campaigns: 115,
    storage_used: 38.7,
    hits_this_month: 510000,
    hit_limit: 600000,
  },
  {
    account_id: "ACC004",
    account_name: "CreativeX Agency",
    email: "team@creativex.co",
    platforms: ["iOS", "Android"],
    current_plan: "essentials",
    status: "active",
    created_at: "2025-02-10T12:00:00Z",
    last_active_at: "2025-12-09T21:30:00Z",
    total_campaigns: 23,
    storage_used: 6.8,
    hits_this_month: 74000,
    hit_limit: 100000,
  },
  {
    account_id: "ACC005",
    account_name: "Direct Sales Client - AlphaCorp",
    email: "sales@alphacorp.com",
    platforms: ["iOS"],
    current_plan: "custom",
    status: "active",
    created_at: "2025-12-01T08:00:00Z",
    last_active_at: "2025-12-09T19:40:00Z",
    total_campaigns: 60,
    storage_used: 25.4,
    hits_this_month: 320000,
    hit_limit: 500000,
  },
];

export const CAMPAIGNS = [
  {
    campaign_id: "CMP001",
    campaign_name: "Winter Sale Blast",
    account: "Techify Labs",
    plan: "growth",
    hits_this_month: 45200,
    total_hits_lifetime: 320450,
    storage_used_by_campaign: 780,
    created_at: "2025-10-05T11:45:00Z",
    status: "active",
  },
  {
    campaign_id: "CMP002",
    campaign_name: "Holiday Deals 2025",
    account: "BlueWave Media",
    plan: "starter",
    hits_this_month: 9800,
    total_hits_lifetime: 40120,
    storage_used_by_campaign: 250,
    created_at: "2025-11-22T08:15:00Z",
    status: "active",
  },
  {
    campaign_id: "CMP003",
    campaign_name: "App Launch Promo",
    account: "TrendBoost",
    plan: "pro_plus",
    hits_this_month: 128000,
    total_hits_lifetime: 1085600,
    storage_used_by_campaign: 2.1,
    created_at: "2024-12-12T15:30:00Z",
    status: "archived",
  },
  {
    campaign_id: "CMP004",
    campaign_name: "Summer Cashback Offer",
    account: "CreativeX Agency",
    plan: "essentials",
    hits_this_month: 36000,
    total_hits_lifetime: 225000,
    storage_used_by_campaign: 650,
    created_at: "2025-06-18T10:10:00Z",
    status: "disabled",
  },
  {
    campaign_id: "CMP005",
    campaign_name: "Enterprise Direct Campaign",
    account: "AlphaCorp (Custom Account)",
    plan: "custom",
    hits_this_month: 78000,
    total_hits_lifetime: 542000,
    storage_used_by_campaign: 3.4,
    created_at: "2025-09-01T09:00:00Z",
    status: "active",
  },
];

export const HIGH_USAGE_ACCOUNTS = [
  {
    account_name: "Alpha Marketing Solutions",
    plan: "pro",
    hits_used: 15230,
    hit_limit: 20000,
    storage_used: "8.2 GB",
    storage_limit: "10 GB",
    number_of_campaigns: 12,
    flag_status: "none",
  },
  {
    account_name: "NextGen Digital Agency",
    plan: "basic",
    hits_used: 4890,
    hit_limit: 10000,
    storage_used: "2.5 GB",
    storage_limit: "5 GB",
    number_of_campaigns: 5,
    flag_status: "warning_near_hit_limit",
  },
  {
    account_name: "Creative Pulse Media",
    plan: "enterprise",
    hits_used: 35300,
    hit_limit: 50000,
    storage_used: "18 GB",
    storage_limit: "25 GB",
    number_of_campaigns: 24,
    flag_status: "none",
  },
  {
    account_name: "Visionary Ads Pvt Ltd",
    plan: "free",
    hits_used: 950,
    hit_limit: 1000,
    storage_used: "480 MB",
    storage_limit: "1 GB",
    number_of_campaigns: 1,
    flag_status: "exceeded_hit_limit",
  },
  {
    account_name: "BlueSky Promotions",
    plan: "pro",
    hits_used: 17300,
    hit_limit: 20000,
    storage_used: "7.4 GB",
    storage_limit: "10 GB",
    number_of_campaigns: 10,
    flag_status: "warning_near_storage_limit",
  },
];

export const CAPACITY_OVERVIEW = [
  {
    total_hits_across_platforms: {
      per_day: 1240,
      per_month: 37200,
    },
    total_storage_used: "52 GB",
    storage_distribution_by_plan: {
      free: "10 GB",
      pro: "25 GB",
      enterprise: "17 GB",
    },
  },
  {
    total_hits_across_platforms: {
      per_day: 870,
      per_month: 26100,
    },
    total_storage_used: "39 GB",
    storage_distribution_by_plan: {
      free: "7 GB",
      pro: "20 GB",
      enterprise: "12 GB",
    },
  },
  {
    total_hits_across_platforms: {
      per_day: 1580,
      per_month: 47400,
    },
    total_storage_used: "65 GB",
    storage_distribution_by_plan: {
      free: "12 GB",
      pro: "30 GB",
      enterprise: "23 GB",
    },
  },
  {
    total_hits_across_platforms: {
      per_day: 640,
      per_month: 19200,
    },
    total_storage_used: "27 GB",
    storage_distribution_by_plan: {
      free: "5 GB",
      pro: "14 GB",
      enterprise: "8 GB",
    },
  },
  {
    total_hits_across_platforms: {
      per_day: 2110,
      per_month: 63300,
    },
    total_storage_used: "82 GB",
    storage_distribution_by_plan: {
      free: "15 GB",
      pro: "40 GB",
      enterprise: "27 GB",
    },
  },
];

export const PLAN_OVERVIEW = [
  {
    plan_name: "starter",
    internal_id: "plan_starter_001",
    monthly_price: 499,
    yearly_price: 4990,
    campaign_limit: 3,
    storage_limit_gb: 5,
    hit_limit_per_month: 10000,
    branding_enabled: true,
  },
  {
    plan_name: "essentials",
    internal_id: "plan_ess_002",
    monthly_price: 999,
    yearly_price: 9990,
    campaign_limit: 10,
    storage_limit_gb: 50,
    hit_limit_per_month: 100000,
    branding_enabled: true,
  },
  {
    plan_name: "growth",
    internal_id: "plan_growth_003",
    monthly_price: 1999,
    yearly_price: 19990,
    campaign_limit: 50,
    storage_limit_gb: 200,
    hit_limit_per_month: 1000000,
    branding_enabled: false,
  },
  {
    plan_name: "pro",
    internal_id: "plan_pro_004",
    monthly_price: 4999,
    yearly_price: 49990,
    campaign_limit: 200,
    storage_limit_gb: 1000,
    hit_limit_per_month: 5000000,
    branding_enabled: false,
  },
  {
    plan_name: "pro_plus",
    internal_id: "plan_pro_plus_005",
    monthly_price: 9999,
    yearly_price: 99990,
    campaign_limit: 1000,
    storage_limit_gb: 5000,
    hit_limit_per_month: 20000000,
    branding_enabled: false,
  },
];

export const ACCOUNT_BILLING_SNAPSHOT = [
  {
    current_plan: "Starter",
    billing_interval: "monthly",
    store_subscription_id: "com.example.starter.001",
    original_purchase_date: "2024-01-15T09:30:00Z",
    last_renewal_timestamp: "2025-12-01T09:30:00Z",
    last_receipt_validation_status: "success",
    expiration_date: "2026-01-01T09:30:00Z",
    cancellation_flag: false,
    refund_flag: false,
    action: "View",
  },
  {
    current_plan: "Essentials",
    billing_interval: "yearly",
    store_subscription_id: "com.example.essentials.002",
    original_purchase_date: "2023-09-10T14:45:00Z",
    last_renewal_timestamp: "2024-09-10T14:45:00Z",
    last_receipt_validation_status: "success",
    expiration_date: "2025-09-10T14:45:00Z",
    cancellation_flag: false,
    refund_flag: false,
    action: "View",
  },
  {
    current_plan: "Growth",
    billing_interval: "monthly",
    store_subscription_id: "com.example.growth.003",
    original_purchase_date: "2024-05-05T12:00:00Z",
    last_renewal_timestamp: "2025-11-05T12:00:00Z",
    last_receipt_validation_status: "failed",
    expiration_date: "2025-12-05T12:00:00Z",
    cancellation_flag: false,
    refund_flag: false,
    action: "Retry",
  },
  {
    current_plan: "Pro",
    billing_interval: "monthly",
    store_subscription_id: "com.example.pro.004",
    original_purchase_date: "2024-07-22T07:15:00Z",
    last_renewal_timestamp: "2025-11-22T07:15:00Z",
    last_receipt_validation_status: "success",
    expiration_date: "2025-12-22T07:15:00Z",
    cancellation_flag: true,
    refund_flag: false,
    action: "View",
  },
  {
    current_plan: "Pro Plus",
    billing_interval: "yearly",
    store_subscription_id: "com.example.proplus.005",
    original_purchase_date: "2023-02-01T18:10:00Z",
    last_renewal_timestamp: "2025-02-01T18:10:00Z",
    last_receipt_validation_status: "success",
    expiration_date: "2026-02-01T18:10:00Z",
    cancellation_flag: false,
    refund_flag: true,
    action: "View",
  },
];

export const STORAGE_BY_ACCOUNT = [
  {
    account_name: "Acme Corp",
    plan: "Pro Annual",
    total_storage_used: "120 GB",
    number_of_media_files: 4800,
    average_file_size: "25 MB",
    oldest_media_date: "2021-03-15",
  },
  {
    account_name: "BlueSky Media",
    plan: "Starter Monthly",
    total_storage_used: "18 GB",
    number_of_media_files: 950,
    average_file_size: "19 MB",
    oldest_media_date: "2022-11-02",
  },
  {
    account_name: "NextGen Studios",
    plan: "Enterprise Annual",
    total_storage_used: "680 GB",
    number_of_media_files: 15200,
    average_file_size: "45 MB",
    oldest_media_date: "2020-07-08",
  },
  {
    account_name: "PixelWorks",
    plan: "Free Trial",
    total_storage_used: "2.5 GB",
    number_of_media_files: 120,
    average_file_size: "21 MB",
    oldest_media_date: "2024-04-22",
  },
  {
    account_name: "GreenTech Solutions",
    plan: "Business Monthly",
    total_storage_used: "72 GB",
    number_of_media_files: 3600,
    average_file_size: "20 MB",
    oldest_media_date: "2021-12-19",
  },
];

export const STORAGE_BY_CAMPAIGN = [
  {
    campaign_id: "CMP-10234",
    account: "Acme Marketing",
    storage_used: "24.8 GB",
    number_of_media_assets: 3560,
  },
  {
    campaign_id: "CMP-20489",
    account: "Zenith Studios",
    storage_used: "145.6 GB",
    number_of_media_assets: 18230,
  },
  {
    campaign_id: "CMP-30512",
    account: "PixelCraft Designs",
    storage_used: "8.9 GB",
    number_of_media_assets: 1260,
  },
  {
    campaign_id: "CMP-40876",
    account: "NextWave Agency",
    storage_used: "33.4 GB",
    number_of_media_assets: 5420,
  },
  {
    campaign_id: "CMP-50934",
    account: "BrightLine Media",
    storage_used: "120.1 GB",
    number_of_media_assets: 15210,
  },
  {
    campaign_id: "CMP-60127",
    account: "UrbanClicks",
    storage_used: "3.7 GB",
    number_of_media_assets: 530,
  },
  {
    campaign_id: "CMP-70945",
    account: "SkyBound Productions",
    storage_used: "58.2 GB",
    number_of_media_assets: 8740,
  },
  {
    campaign_id: "CMP-81063",
    account: "OmniReach Digital",
    storage_used: "208.4 GB",
    number_of_media_assets: 24560,
  },
];

export const FLAGS_AND_ABUSE = [
  {
    account: "Acme Marketing",
    campaign: "CMP-10234",
    flag_type: "Hit spike anomaly",
    reason: "auto",
    status: "Under Review",
    created_at: "2025-12-10 14:22:30",
    last_updated: "2025-12-11 09:45:10",
  },
  {
    account: "Zenith Studios",
    campaign: "CMP-20489",
    flag_type: "Storage abuse",
    reason: "auto",
    status: "Open",
    created_at: "2025-12-08 10:05:44",
    last_updated: "2025-12-09 16:32:20",
  },
  {
    account: "PixelCraft Designs",
    campaign: "",
    flag_type: "DMCA / content complaint",
    reason: "manual",
    status: "Resolved",
    created_at: "2025-11-29 12:40:05",
    last_updated: "2025-12-01 08:10:22",
  },
  {
    account: "NextWave Agency",
    campaign: "CMP-40876",
    flag_type: "Suspicious traffic",
    reason: "auto",
    status: "Under Review",
    created_at: "2025-12-09 07:58:33",
    last_updated: "2025-12-11 08:20:14",
  },
  {
    account: "BrightLine Media",
    campaign: "CMP-50934",
    flag_type: "App Store complaint",
    reason: "manual",
    status: "Open",
    created_at: "2025-12-07 09:10:00",
    last_updated: "2025-12-10 13:30:45",
  },
  {
    account: "UrbanClicks",
    campaign: "CMP-60127",
    flag_type: "Storage abuse",
    reason: "auto",
    status: "Resolved",
    created_at: "2025-11-20 15:25:18",
    last_updated: "2025-12-05 11:14:29",
  },
];

export const PRICING_PLANS = [
  {
    id: "personal",
    name: "Personal",
    price_per_month: 3,
    price_per_year: 36,
    billing_cycle: "Annually",
    description:
      "One campaign, unlimited potential. The simplest way to launch your first video QR.",
    benefits: {
      campaigns: 1,
      storage: "100MB",
      scans_per_month: 500,
      branding: "#PoweredbyVidCode Branding",
    },
    recommended: false,
  },
  {
    id: "starter",
    name: "Starter",
    price_per_month: 6,
    price_per_year: 72,
    billing_cycle: "Annually",
    description:
      "More campaigns, same simplicity. Great for creators getting serious.",
    benefits: {
      campaigns: 10,
      storage: "250MB",
      scans_per_month: 1000,
      branding: "#PoweredbyVidCode Branding",
    },
    recommended: false,
  },
  {
    id: "essential",
    name: "Essential",
    price_per_month: 12,
    price_per_year: 144,
    billing_cycle: "Annually",
    description:
      "Enough campaigns and storage to run real marketing, not just experiments.",
    benefits: {
      campaigns: 25,
      storage: "1GB",
      hits_per_month: 5000,
      branding: "#PoweredbyVidCode Branding",
    },
    recommended: false,
  },
  {
    id: "growth",
    name: "Growth",
    price_per_month: 20,
    price_per_year: 240,
    billing_cycle: "Annually",
    description:
      "Built for real businesses. Manage dozens of campaigns and scale your video QR strategy.",
    benefits: {
      campaigns: 75,
      storage: "5GB",
      hits_per_month: 15000,
      branding: "No #PoweredbyVidCode Branding",
    },
    recommended: true,
  },
  {
    id: "pro",
    name: "Pro",
    price_per_month: 35,
    price_per_year: 420,
    billing_cycle: "Annually",
    description:
      "Run more campaigns, capture more conversions. Built for growing brands pushing video at scale.",
    benefits: {
      campaigns: 150,
      storage: "10GB",
      hits_per_month: 50000,
      branding: "No #PoweredbyVidCode Branding",
    },
    recommended: false,
  },
  {
    id: "pro_plus",
    name: "Pro Plus",
    price_per_month: 65,
    price_per_year: 780,
    billing_cycle: "Annually",
    description:
      "Big volume, real performance. The go-to plan for agencies, teams, and multi-campaign power users.",
    benefits: {
      campaigns: 300,
      storage: "25GB",
      hits_per_month: 150000,
      branding: "No #PoweredbyVidCode Branding",
    },
    recommended: false,
  },
];
